#!/bin/bash
sudo yum install update

#The next two are necessary for pip to run without failing with error 'Command "python setup.py egg_info" failed with error code 1':
sudo yum groupinstall "Development Tools"
sudo yum install python-devel libpng-devel freetype-devel

#This takes at least ten minutes:
sudo pip install matplotlib pandas #Finally it works!

